spring.application.name=notification-server

logging.level.com.emcrey=DEBUG

spring.config.import=\optional:file:/app/configuration/processes/notification-server/notification-server.properties,\optional:file:/app/configuration/processes/notification-server/jdbc.properties

# Whatsapp Configuration
notification.server.whatsapp.api-version=v25.0
notification.server.whatsapp.phone-number-id=1192576443938526
notification.server.whatsapp.access-token=EAAbcsqr2pl4BRxZA33sPHZCzSKRIsXd36mwQd4CXKG0WMV1LEX1HsLaAi5rrOVGhT2BZCE3rXZC9NZA50QsqxkqhQZAcsfZACFHddxQ02f7wN3ccFtCKa1yTM88qLruzFQUyexKlAeLatJnUpdQF1HyXi0ZCev4BSnAky03mccOecmQZCuzrly1HJhDbL086YvBwnvBwuXAfZCeTKUQmM6ssDtK9neOsnq6j6aTg3a
