spring.application.name=wasselni-web-service
springdoc.swagger-ui.path=/index.html
springdoc.api-docs.path=/v3/api-docs

spring.config.import=optional:file:/app/configuration/web-service/web-service.properties

server.port=${PORT:8080}
server.servlet.context-path=/web-service

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.path=/

logging.level.com.wasselni=DEBUG