web.service.env.isDev=true
web.service.api.request.timeout=10000
web.service.application.id=2
web.service.allowed.hosts=*,wasselni-backend.onrender.com,https://wasselni-backend.onrender.com

web.service.jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3CFfnBFwAJUWk/Z6Ea+1Z+O86l0al1ZH0pJE+fPKiVp51z9COERXhb3iMd3grEXBV2fqxd7RDOLCC+T01H7QmPMb7m3HdNt3ziRdmACQb5abrR7vxoDqm88S31vxQhO5P/4jtLK1sclwTlOq2QxQHglRMT+REKMmitKN9mV7ygxTwPqL1k+BHnBK2soRT4hhd9xPpS30azwv0XT56SLRZIgmBQXKQhnz7W3ie5BVKpZZTjRcB9SwLYbbBXDqSYA3VEqbHmSMSJ5mEzcVQmt59rLh6ybU8fxR4/CTPLWGihQcPqyg/T+x7kTa4VPaDW00YvA8dm43jPr0XtWUFu11uQIDAQAB

web.service.env.otp.validity=2

web.service.core.server.tcp.host=127.0.0.1
web.service.core.server.tcp.port=9090
web.service.core.server.tcp.timeout=30000