spring.main.web-application-type=none

spring.config.import=optional:file:/app/configuration/core-server/core-server.properties,optional:file:/app/configuration/core-server/jdbc.properties

logging.level.com.wasselni=DEBUG