#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/wasselni?currentSchema=wasselni
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-dawn-meadow-ai3z6lrz-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_W0PKwZxiSIF2
spring.datasource.hikari.schema=wasselni

spring.jpa.properties.hibernate.default_schema=wasselni

spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false